/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControllerCadFornecedor;
import controller.ControllerCadFuncionario;
import controller.ControllerCadHospedes;
import controller.ControllerMarca_Original;
import controller.ControllerCadModelo;
import controller.ControllerCadProdutoCopa;
import controller.ControllerCadQuarto;
import controller.ControllerCadServico;
import controller.ControllerCadVagaEstacionamento;
import controller.ControllerCadVeiculo;
import controller.JavaTest;
import java.time.LocalDate;
import javax.swing.JOptionPane;

/**
 *
 * @author aluno
 */
public class TelaMenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaMenuPrincipal
     */
    public TelaMenuPrincipal() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }
    private String retorno;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuPrincipal = new javax.swing.JMenuBar();
        jMenuCadastros = new javax.swing.JMenu();
        jMenuItemFornecedor = new javax.swing.JMenuItem();
        jMenuItemFuncionario = new javax.swing.JMenuItem();
        jMenuItemHospede = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemQuarto = new javax.swing.JMenuItem();
        jMenuItemServico = new javax.swing.JMenuItem();
        jMenuItemProduto = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItemVagaEstacionamento = new javax.swing.JMenuItem();
        jMenuItemVeiculo = new javax.swing.JMenuItem();
        jMenuItemModelo = new javax.swing.JMenuItem();
        jMenuItemMarca = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItemSair = new javax.swing.JMenuItem();
        jMenuMovimentos = new javax.swing.JMenu();
        jMenuRelatorios = new javax.swing.JMenu();
        jMenuAjuda = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuSobre = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));

        jMenuPrincipal.setBackground(new java.awt.Color(204, 204, 204));

        jMenuCadastros.setBackground(new java.awt.Color(204, 204, 204));
        jMenuCadastros.setForeground(new java.awt.Color(102, 102, 102));
        jMenuCadastros.setText("Cadastros");

        jMenuItemFornecedor.setBackground(new java.awt.Color(204, 204, 204));
        jMenuItemFornecedor.setForeground(new java.awt.Color(102, 102, 102));
        jMenuItemFornecedor.setText("Fornecedor");
        jMenuItemFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFornecedorActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemFornecedor);

        jMenuItemFuncionario.setBackground(new java.awt.Color(204, 204, 204));
        jMenuItemFuncionario.setForeground(new java.awt.Color(102, 102, 102));
        jMenuItemFuncionario.setText("Funcionário");
        jMenuItemFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFuncionarioActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemFuncionario);

        jMenuItemHospede.setBackground(new java.awt.Color(204, 204, 204));
        jMenuItemHospede.setForeground(new java.awt.Color(102, 102, 102));
        jMenuItemHospede.setText("Hóspede");
        jMenuItemHospede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemHospedeActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemHospede);
        jMenuCadastros.add(jSeparator1);

        jMenuItemQuarto.setBackground(new java.awt.Color(204, 204, 204));
        jMenuItemQuarto.setForeground(new java.awt.Color(102, 102, 102));
        jMenuItemQuarto.setText("Quarto");
        jMenuItemQuarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemQuartoActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemQuarto);

        jMenuItemServico.setBackground(new java.awt.Color(204, 204, 204));
        jMenuItemServico.setForeground(new java.awt.Color(102, 102, 102));
        jMenuItemServico.setText("Serviço");
        jMenuItemServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemServicoActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemServico);

        jMenuItemProduto.setBackground(new java.awt.Color(204, 204, 204));
        jMenuItemProduto.setForeground(new java.awt.Color(102, 102, 102));
        jMenuItemProduto.setText("Produto");
        jMenuItemProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemProdutoActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemProduto);
        jMenuCadastros.add(jSeparator3);

        jMenuItemVagaEstacionamento.setBackground(new java.awt.Color(204, 204, 204));
        jMenuItemVagaEstacionamento.setForeground(new java.awt.Color(102, 102, 102));
        jMenuItemVagaEstacionamento.setText("Estacionamento");
        jMenuItemVagaEstacionamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVagaEstacionamentoActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemVagaEstacionamento);

        jMenuItemVeiculo.setBackground(new java.awt.Color(204, 204, 204));
        jMenuItemVeiculo.setForeground(new java.awt.Color(102, 102, 102));
        jMenuItemVeiculo.setText("Veículo");
        jMenuItemVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVeiculoActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemVeiculo);

        jMenuItemModelo.setBackground(new java.awt.Color(204, 204, 204));
        jMenuItemModelo.setForeground(new java.awt.Color(102, 102, 102));
        jMenuItemModelo.setText("Modelo");
        jMenuItemModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemModeloActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemModelo);

        jMenuItemMarca.setBackground(new java.awt.Color(204, 204, 204));
        jMenuItemMarca.setForeground(new java.awt.Color(102, 102, 102));
        jMenuItemMarca.setText("Marca");
        jMenuItemMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMarcaActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemMarca);
        jMenuCadastros.add(jSeparator2);

        jMenuItemSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Exit.png"))); // NOI18N
        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemSair);

        jMenuPrincipal.add(jMenuCadastros);

        jMenuMovimentos.setBackground(new java.awt.Color(204, 204, 204));
        jMenuMovimentos.setForeground(new java.awt.Color(102, 102, 102));
        jMenuMovimentos.setText("Movimentos");
        jMenuPrincipal.add(jMenuMovimentos);

        jMenuRelatorios.setBackground(new java.awt.Color(204, 204, 204));
        jMenuRelatorios.setForeground(new java.awt.Color(102, 102, 102));
        jMenuRelatorios.setText("Relatórios");
        jMenuPrincipal.add(jMenuRelatorios);

        jMenuAjuda.setBackground(new java.awt.Color(204, 204, 204));
        jMenuAjuda.setForeground(new java.awt.Color(102, 102, 102));
        jMenuAjuda.setText("Ajuda");

        jMenuItem1.setText("TestJava");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuAjuda.add(jMenuItem1);

        jMenuPrincipal.add(jMenuAjuda);

        jMenuSobre.setBackground(new java.awt.Color(204, 204, 204));
        jMenuSobre.setForeground(new java.awt.Color(102, 102, 102));
        jMenuSobre.setText("Sobre");
        jMenuPrincipal.add(jMenuSobre);

        setJMenuBar(jMenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 754, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 464, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        dispose();
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jMenuItemHospedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemHospedeActionPerformed
        CadastroHospedes telaCadastroHospedes = new CadastroHospedes(null, true);
        ControllerCadHospedes controllerCadHospedes = new ControllerCadHospedes(telaCadastroHospedes);
        telaCadastroHospedes.setVisible(true);
    }//GEN-LAST:event_jMenuItemHospedeActionPerformed

    private void jMenuItemFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFuncionarioActionPerformed
        CadastroFuncionarios telaCadastroFuncionarios = new CadastroFuncionarios(null, true);
        ControllerCadFuncionario controllerCadFuncinarios = new ControllerCadFuncionario(telaCadastroFuncionarios);
        telaCadastroFuncionarios.setVisible(true);
    }//GEN-LAST:event_jMenuItemFuncionarioActionPerformed

    private void jMenuItemFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFornecedorActionPerformed
        // TODO add your handling code here:
        CadastroFornecedores telaCadastroFornecedores = new CadastroFornecedores(null, true);
        ControllerCadFornecedor controllerCadFornecedor = new ControllerCadFornecedor(telaCadastroFornecedores);
        telaCadastroFornecedores.setVisible(true);
    }//GEN-LAST:event_jMenuItemFornecedorActionPerformed

    private void jMenuItemQuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemQuartoActionPerformed
        // TODO add your handling code here:
        CadastroQuarto telaCadastroQuarto = new CadastroQuarto(null, true);
        ControllerCadQuarto controllerCadQuarto = new ControllerCadQuarto(telaCadastroQuarto);
        telaCadastroQuarto.setVisible(true);
    }//GEN-LAST:event_jMenuItemQuartoActionPerformed

    private void jMenuItemServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemServicoActionPerformed
        // TODO add your handling code here:
        CadastroServico telaCadastroServico = new CadastroServico(null, true);
        ControllerCadServico controllerCadServico = new ControllerCadServico(telaCadastroServico);
        telaCadastroServico.setVisible(true);
    }//GEN-LAST:event_jMenuItemServicoActionPerformed

    private void jMenuItemProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemProdutoActionPerformed
        // TODO add your handling code here:
        CadastroProdutoCopa telaCadastroProdutoCopa = new CadastroProdutoCopa(null, true);
        ControllerCadProdutoCopa controllerCadProdutoCopa = new ControllerCadProdutoCopa(telaCadastroProdutoCopa);
        telaCadastroProdutoCopa.setVisible(true);
    }//GEN-LAST:event_jMenuItemProdutoActionPerformed

    private void jMenuItemVagaEstacionamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVagaEstacionamentoActionPerformed
        // TODO add your handling code here:
        CadastroVagaEstacionamento telaCadastroVagaEstacionamento = new CadastroVagaEstacionamento(null, true);
        ControllerCadVagaEstacionamento controllerCadVagaEstacionamento = new ControllerCadVagaEstacionamento(telaCadastroVagaEstacionamento);
        telaCadastroVagaEstacionamento.setVisible(true);
    }//GEN-LAST:event_jMenuItemVagaEstacionamentoActionPerformed

    private void jMenuItemVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVeiculoActionPerformed
        // TODO add your handling code here:
        CadastroVeiculo telaCadastroVeiculo = new CadastroVeiculo(null, true);
        ControllerCadVeiculo controllerCadVeiculo = new ControllerCadVeiculo(telaCadastroVeiculo);
        telaCadastroVeiculo.setVisible(true);
    }//GEN-LAST:event_jMenuItemVeiculoActionPerformed

    private void jMenuItemModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemModeloActionPerformed
        // TODO add your handling code here:
        CadastroModelo telaCadastroModelo = new CadastroModelo(null, true);
        ControllerCadModelo controllerCadModelo = new ControllerCadModelo(telaCadastroModelo);
        telaCadastroModelo.setVisible(true);
    }//GEN-LAST:event_jMenuItemModeloActionPerformed

    private void jMenuItemMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMarcaActionPerformed
        // TODO add your handling code here:
        CadastroMarca telaCadastroMarca = new CadastroMarca(null, true);
        ControllerMarca_Original controllerCadMarca = new ControllerMarca_Original(telaCadastroMarca);
        telaCadastroMarca.setVisible(true);
    }//GEN-LAST:event_jMenuItemMarcaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        //JavaTest jt = new JavaTest();
        //jt.retornaMarca1();
        //testa cpf
        String i = JOptionPane.showInputDialog("insira cpf");
        JOptionPane.showMessageDialog(null, utilities.Utilities.validaCpf(i));
        /*do{
            String i = JOptionPane.showInputDialog("insira data (dd/MM/yyyy)");
            this.retorno = utilities.Utilities.validaDataString(i);
            JOptionPane.showMessageDialog(null,retorno);
        }while (this.retorno.equals("Informe uma data válida!"));*/
        /*String a = JOptionPane.showInputDialog("insira data antiga:");
        JOptionPane.showMessageDialog(null, utilities.Utilities.validaDataAntigaString(a, LocalDate.now()));
        String f = JOptionPane.showInputDialog("insira data futura:");
        JOptionPane.showMessageDialog(null, utilities.Utilities.validaDataFuturaString(f, LocalDate.now()));*/
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenuAjuda;
    private javax.swing.JMenu jMenuCadastros;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemFornecedor;
    private javax.swing.JMenuItem jMenuItemFuncionario;
    private javax.swing.JMenuItem jMenuItemHospede;
    private javax.swing.JMenuItem jMenuItemMarca;
    private javax.swing.JMenuItem jMenuItemModelo;
    private javax.swing.JMenuItem jMenuItemProduto;
    private javax.swing.JMenuItem jMenuItemQuarto;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenuItem jMenuItemServico;
    private javax.swing.JMenuItem jMenuItemVagaEstacionamento;
    private javax.swing.JMenuItem jMenuItemVeiculo;
    private javax.swing.JMenu jMenuMovimentos;
    private javax.swing.JMenuBar jMenuPrincipal;
    private javax.swing.JMenu jMenuRelatorios;
    private javax.swing.JMenu jMenuSobre;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
